services:
  - type: web
    name: portfolio-website
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm install -D tailwindcss postcss autoprefixer
      npx tailwindcss init -p
      rm -rf .next
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_HUGGINGFACE_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: RECIPIENT_PHONE_NUMBER
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        sync: false 